services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario-api
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ConnectionStrings__DefaultConnection: >-
        Server=${DB_HOST:-161.97.69.127};Port=${DB_PORT:-3370};Database=examen_unidad;User=${DB_USER:-nicolerios};Password=${DB_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URL: http://+:8080
      Cors__AllowedOrigins__0: http://localhost:5173
      Cors__AllowedOrigins__1: http://localhost:3000
      Cors__AllowedOrigins__2: http://localhost:4173
      Cors__AllowedOrigins__3: https://inventario-celulares-beta.vercel.app
    ports:
      - "5080:8080"
